# Site settings
title: Dylan Conlin
email: dylan.conlin@gmail.com
description: "This is Dylan Conlin's blog. It should be here for awhile."
baseurl: ""
url: "www.dylanconlin.com"

# Build settings
markdown: kramdown
permalink: pretty
